### ISSUE TITLE
How to Change the Font in Overleaf?

### ISSUE THREAD

**Issue by criticalfault** [TrueLunacy/HolostreetsLatex#3]
You may want to include some of this in your Markdown for your readme. I'm a complete noob though. Someone told me to use overleaf, so im learning it and it took me 20 minutes to figure out how to change the dang engine.

![image](https://github.com/TrueLunacy/HolostreetsLatex/assets/15347342/8684bf5f-a8e0-45fc-87d9-712616f908c2)

![image](https://github.com/TrueLunacy/HolostreetsLatex/assets/15347342/26ccc056-5e74-45be-9bdb-2eefc24111a2)

All of that said, i still cant figure out how to get my fonts to be targeted now that ive uploaded them.

**Comment by TrueLunacy** [comment]
Hey! I'm sorry to say I'm not completely sure how to help you. I don't use Overleaf myself, so if it's got any idiosyncracies or anything extra required, I can't help much. But, you can change the fonts to the presets available by using options on the document class, same as you would for the general sheet colour.

If you want completely custom fonts, you'll have to set them manually. We use five font families. The main font and monospace font can be set with \setmainfont{...} and
\setmonofont{...}, while the other three font families can be set with \setfontfamily\titlefont{...}, \setfontfamily\headerfont{...} and \setfontfamily\tablefont{...}.

This stuff would be good to have in the documentation, and I'll probably get around to adding it Eventually ™️ , but this whole thing is beta-quality right now. And unfortunately not beta as in betaware. As for Overleaf specific stuff, I'd be happy to accept pull requests that gave documentation for it, but I don't use it myself so I wouldn't know where to start on how to make it work.

**Comment by criticalfault** [comment]
So after doing some work on it tonight I did get it to work and I can detail how I did it tomorrow and put in a pull request for the mark down updates if you'd like. 

This thing works like gangbusters man. It's made a beautiful template and it looks professionally done. 

Thanks for all of your hard work!!

**Comment by TrueLunacy** [comment]
I've also pushed an update that should make some things more clear in the documentation, as well as fix spacing for long chapter titles.
